'use client';
import { useState } from 'react';
import { ArrowRight, Search, Layers, Truck, SlidersHorizontal, Globe, Check, UserRound, ShoppingBag } from 'lucide-react';
import picks from '../data/home-edit.json';
import { BrandDirectory } from './brand-directory';
import './brand-showcase.css';
import './home-street.css';
export function HomeEditorial({browse,navigate}:{browse:(category?:string)=>void;navigate:(view:string)=>void}){
 const [search,setSearch]=useState('');
 const [brandsOpen,setBrandsOpen]=useState(false);
 const cards=['Clothing','Shoes','Watches','Bags','Accessories'].map(label=>({label,image:'/category-art/'+label.toLowerCase()+'.png',style:'category-cutout'}));
 return <div className="street-home">
 <div className="street-announcement"><span>Free worldwide shipping</span><span>Premium replicas. Luxury looks for less.</span><span>Prices in DKK</span></div>
 <header className="street-header"><button className="street-logo" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}>OUTOUF</button><nav aria-label="Home navigation"><a href="#">Home</a><button onClick={()=>browse()}>Shop</button><a href="#collections">Collections</a><a href="#brand-list" onClick={()=>setBrandsOpen(true)}>Brands</a><a href="#street-edit">The Edit</a></nav><form onSubmit={e=>{e.preventDefault();window.location.assign(`/?search=${encodeURIComponent(search)}`);}}><Search size={15}/><input aria-label="Search products" placeholder="Search for products…" value={search} onChange={e=>setSearch(e.target.value)}/></form><div className="street-icons"><button aria-label="Account" onClick={()=>navigate('account')}><UserRound size={20}/></button><button aria-label="Shopping bag" onClick={()=>navigate('cart')}><ShoppingBag size={20}/></button></div></header>
 <section className="street-hero"><img src="/editorial/street-hero.png" alt="Streetwear campaign with oversized denim, layered jackets and relaxed silhouettes" fetchPriority="high"/><div className="street-hero-copy"><p className="street-kicker">PREMIUM REPLICAS · EVERYDAY PRICES</p><h1>Star Style. <br/>Your Budget.</h1><p>Dress like a star, spend your way.<br/>Discover luxury-brand replicas for less.<br/>Free shipping, wherever you call home.</p><div className="street-actions"><button onClick={()=>browse()}>Shop the collection <ArrowRight size={15}/></button><a href="#street-edit">The Outouf Edit</a></div><div className="street-stats"><div><b>175</b><span>Brand styles to explore</span></div><div><b>10</b><span>Product categories</span></div><div><b>Worldwide</b><span>Always free shipping</span></div></div></div></section>
 <div className="street-content"><section className="street-categories" id="collections" aria-label="Categories">{cards.map(c=><button key={c.label} onClick={()=>browse(c.label)} className={c.style}><img src={c.image} alt=""/><span><b>{c.label}</b><small>Shop now <ArrowRight size={13}/></small></span></button>)}</section>
 <div className="street-benefits">{[[Layers,'Premium replicas','Luxury looks for less'],[Truck,'Free shipping','On every order'],[SlidersHorizontal,'Find your fit','Filter by brand and size'],[Globe,'Worldwide delivery','Style without borders']].map(([Icon,title,subtitle])=><div key={String(title)}>{typeof Icon!=='string'&&<Icon size={25}/>}<p><b>{String(title)}</b><span>{String(subtitle)}</span></p></div>)}</div>
 <section className="street-banner" id="street-edit"><img src="/editorial/street-banner.png" alt="Denim, a utility jacket, trail sneakers and a crossbody bag in an industrial studio" loading="lazy"/><div><p className="street-kicker">THE LUXURY LOOK, REIMAGINED</p><h2>Big Style.<br/>Smaller Spend.</h2><p>Star-inspired looks. Premium replicas.<br/>Make the look your own for less.</p><button onClick={()=>browse('Clothing')}>Explore collection <ArrowRight size={15}/></button></div></section>
 <section className="street-promos">{[{name:'Details that matter',cat:'Watches',image:`/brand-cutouts/${picks[3].id}.png`},{name:'Everyday footwear',cat:'Shoes',image:'/editorial/sneaker-campaign.png'},{name:'Carry your world',cat:'Bags',image:`/brand-cutouts/${picks[2].id}.png`}].map(p=><button key={p.cat} onClick={()=>browse(p.cat)}><img src={p.image} alt=""/><span>{p.name}<small>Shop now →</small></span></button>)}</section>
 <section className="street-mobile"><div className="street-phone"><img src="/editorial/sneaker-campaign.png" alt="Industrial sneaker campaign" loading="lazy"/><span>OUTOUF</span></div><div><h2>Your next find.<br/>Anywhere.</h2><p>Explore the full collection on your phone.<br/>Premium replicas. Free worldwide shipping.</p><button onClick={()=>browse()}>Explore the collection <ArrowRight size={15}/></button></div><ul>{['Replica styles across 175 brands','Clothing, footwear & accessories','Free worldwide shipping','Filter by brand and size'].map(t=><li key={t}><Check size={17}/>{t}</li>)}</ul></section>
 <details className="street-brand-list" id="brand-list" open={brandsOpen} onToggle={e=>setBrandsOpen(e.currentTarget.open)}><summary>Explore replicas by brand <span>+</span></summary><BrandDirectory/></details>
 <section className="street-disclosure" aria-label="About our products"><h2>Know what you’re shopping.</h2><p>All products sold by Outouf are replicas, not original branded goods. Brand names identify the styles in our collection. Outouf is not affiliated with or endorsed by these brands.</p></section></div><footer className="street-footer"><div><h2>The look you love. For less.</h2><p>Premium replicas, delivered worldwide with free shipping.</p></div><button onClick={()=>browse()}>Discover Outouf <ArrowRight size={16}/></button></footer>
 </div>;
}
