"use client";

import { ArrowRight, BadgeDollarSign, Check, ChevronRight, Heart, Package, Search, ShoppingBag, Sparkles, UserRound, Wallet, Minus, Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import "./commerce.css";

const categories = [["Clothing", "Soft layers for every day", "lilac"], ["Shoes", "The pair that goes anywhere", "lemon"], ["Watches", "Small details, big feeling", "mint"], ["Bags", "Carry more of your world", "peach"], ["Jewelry", "Little things, greater meaning", "sky"], ["Perfume", "A more conscious ritual", "rose"]];
const orders = [
  { id: "#OTF-1048", customer: "Maya L.", item: "Everyday shoulder bag", total: "84.00 USDC", affiliate: "Nora’s link", status: "Ready to validate" },
  { id: "#OTF-1047", customer: "Alex M.", item: "Satin scarf + sunglasses", total: "42.00 USDC", affiliate: "Direct", status: "Sourcing" },
  { id: "#OTF-1046", customer: "Sofia R.", item: "Classic gold watch", total: "116.00 USDC", affiliate: "Nora’s link", status: "Validated" },
];

export default function Home() {
  const [view, setView] = useState<"shop" | "wallet" | "community" | "orders" | "cart">("shop");
  const [notice, setNotice] = useState("Your wallet is ready for your next find.");
  const [validated, setValidated] = useState<string[]>(["#OTF-1046"]);
  const [cart, setCart] = useState<{ name: string; price: number; color: string; quantity: number }[]>([]);
  const addToCart = (name: string, price: number, color: string) => { setCart((current) => { const existing = current.find((item) => item.name === name); return existing ? current.map((item) => item.name === name ? { ...item, quantity: item.quantity + 1 } : item) : [...current, { name, price, color, quantity: 1 }]; }); setNotice(`${name} added to your bag.`); };
  const updateQuantity = (name: string, by: number) => setCart((current) => current.flatMap((item) => item.name !== name ? [item] : item.quantity + by < 1 ? [] : [{ ...item, quantity: item.quantity + by }]));
  const validateOrder = (id: string) => { if (!validated.includes(id)) setValidated((x) => [...x, id]); setNotice(`Order ${id} validated — affiliate reward credited automatically.`); };
  return <main className="site-shell">
    <header className="topbar">
      <button className="brand" onClick={() => setView("shop")} aria-label="Outouf home">OUTOUF</button>
      <nav aria-label="Main navigation" className="main-nav"><button onClick={() => setView("shop")}>Shop</button><button onClick={() => setView("community")}>Community</button><button onClick={() => setView("orders")}>Orders</button></nav>
      <div className="header-actions"><button className="round-button" aria-label="Search"><Search size={19} /></button><button className="wallet-chip" onClick={() => setView("wallet")}><span>◎</span> USDC&nbsp; 245.00 <ChevronRight size={15} /></button><button className="round-button" aria-label="Saved items"><Heart size={19} /></button><button className="round-button" aria-label="Account"><UserRound size={19} /></button><button className="round-button cart" aria-label="Shopping bag" onClick={() => setView("cart")}><ShoppingBag size={19} />{cart.length > 0 && <b>{cart.reduce((total, item) => total + item.quantity, 0)}</b>}</button></div>
    </header>
    <div className="status-line" role="status"><Sparkles size={15} /> {notice}</div>
    {view === "shop" && <Shop onWallet={() => setView("wallet")} onCommunity={() => setView("community")} onAdd={addToCart} />}
    {view === "wallet" && <WalletView onShop={() => setView("shop")} setNotice={setNotice} />}
    {view === "community" && <CommunityView setNotice={setNotice} />}
    {view === "orders" && <OrdersView validated={validated} validateOrder={validateOrder} />}
    {view === "cart" && <CartView cart={cart} onUpdate={updateQuantity} onShop={() => setView("shop")} onCheckout={() => { if (!cart.length) return setNotice("Your bag is empty — add a piece before checking out."); setCart([]); setNotice("Payment confirmed with USDC. Your order is now pending validation."); setView("orders"); }} />}
  </main>;
}

function Shop({ onWallet, onCommunity, onAdd }: { onWallet: () => void; onCommunity: () => void; onAdd: (name: string, price: number, color: string) => void }) { return <>
  <section className="hero"><img src="/outouf-hero.png" alt="Curated unbranded fashion accessories arranged in a warm studio" /><div className="hero-copy"><p className="eyebrow">CURATED FOR YOUR NEXT LOOK</p><h1>Discover your<br /><strong>next piece.</strong></h1><p>Clothes, shoes, bags, watches, jewelry, perfume and scarves—chosen for a brighter you.</p><button className="primary-button" onClick={onWallet}>SHOP WITH USDC <ArrowRight size={18} /></button><div className="hero-dots"><i className="active" /><i /><i /></div></div><button className="hero-arrow left" aria-label="Previous collection">‹</button><button className="hero-arrow right" aria-label="Next collection">›</button></section>
  <section className="section-head"><h2>Fresh drops</h2><button>See all <ArrowRight size={16} /></button></section>
  <section className="category-grid" aria-label="Shop by category">{categories.map(([name, description, color], index) => <article className={`category-card ${color}`} key={name}><div className="category-object" aria-hidden="true"><span>{["✦", "◒", "◷", "◖", "✧", "◌"][index]}</span></div><div><p>{name}</p><small>{description}</small></div><button aria-label={`Browse ${name}`}><ArrowRight size={17} /></button></article>)}</section>
  <section className="section-head product-head"><div><p className="eyebrow">CURATED THIS WEEK</p><h2>Pieces to know now</h2></div><button>View all <ArrowRight size={16} /></button></section>
  <section className="product-rail"><Product name="Summer silk scarf" price={28} color="pale-pink" onAdd={onAdd} /><Product name="Soft leather shoulder bag" price={84} color="sand" onAdd={onAdd} /><Product name="Everyday gold watch" price={116} color="soft-blue" onAdd={onAdd} /></section>
  <section className="earn-banner"><div className="earn-portrait" aria-hidden="true">✦</div><div><p className="eyebrow">SHARE • EARN • GROW</p><h2>Earn with OUTOUF</h2><p>Share what you love. When a friend’s order is validated, your USDC reward lands automatically.</p></div><button className="primary-button" onClick={onCommunity}>VIEW YOUR REWARDS <ArrowRight size={18} /></button><div className="earn-steps"><span><b>1</b> Share</span><span><b>2</b> Shop</span><span><b>3</b> Earn</span></div></section>
</>; }

function Product({ name, price, color, onAdd }: { name: string; price: number; color: string; onAdd: (name: string, price: number, color: string) => void }) { return <article className="product-card"><div className={`product-art ${color}`}><span>✦</span></div><div className="product-info"><div><p>{name}</p><small>Available now</small></div><strong>{price}.00 USDC</strong></div><button className="add-button" onClick={() => onAdd(name, price, color)}>ADD TO BAG <Plus size={16} /></button></article>; }

function CartView({ cart, onUpdate, onShop, onCheckout }: { cart: { name: string; price: number; color: string; quantity: number }[]; onUpdate: (name: string, by: number) => void; onShop: () => void; onCheckout: () => void }) { const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0); return <section className="app-page cart-page"><div className="page-intro split"><div><p className="eyebrow">YOUR BAG</p><h1>Ready when you are.</h1><p>Checkout is paid with your available USDC balance.</p></div><button className="text-button" onClick={onShop}>← Continue shopping</button></div>{cart.length === 0 ? <div className="empty-bag"><ShoppingBag size={34} /><h2>Your bag is empty</h2><p>Find something that feels like you.</p><button className="primary-button" onClick={onShop}>BROWSE DROPS <ArrowRight size={17} /></button></div> : <div className="cart-layout"><div className="cart-items">{cart.map((item) => <article className="cart-item" key={item.name}><div className={`cart-thumb ${item.color}`}>✦</div><div><h2>{item.name}</h2><p>Curated drop · Ready to source</p><strong>{item.price}.00 USDC</strong></div><div className="quantity"><button onClick={() => onUpdate(item.name, -1)} aria-label="Decrease quantity"><Minus size={15} /></button><b>{item.quantity}</b><button onClick={() => onUpdate(item.name, 1)} aria-label="Increase quantity"><Plus size={15} /></button></div><button className="remove" onClick={() => onUpdate(item.name, -item.quantity)} aria-label={`Remove ${item.name}`}><Trash2 size={18} /></button></article>)}</div><aside className="checkout-card"><p className="eyebrow">ORDER SUMMARY</p><div><span>Items</span><b>{total}.00 USDC</b></div><div><span>Shipping</span><b>Calculated after sourcing</b></div><hr /><div className="total"><span>Total today</span><strong>{total}.00 USDC</strong></div><button className="primary-button" onClick={onCheckout}>PAY WITH USDC <ArrowRight size={17} /></button><small>Available wallet balance: 245.00 USDC</small></aside></div>}</section>; }

function WalletView({ onShop, setNotice }: { onShop: () => void; setNotice: (text: string) => void }) { return <section className="app-page wallet-page"><div className="page-intro"><p className="eyebrow">CUSTODIAL WALLET</p><h1>Your OUTOUF balance</h1><p>Use USDC for purchases and keep every payment in one clear place.</p></div><div className="wallet-layout"><article className="balance-card"><p>AVAILABLE BALANCE</p><h2>245.00 <span>USDC</span></h2><div><button className="primary-button" onClick={() => setNotice("USDC purchase flow opened — add funds securely with your card.")}>BUY USDC <ArrowRight size={17} /></button><button className="secondary-button" onClick={() => setNotice("Deposit details are ready to copy.")}>DEPOSIT</button></div></article><article className="activity-card"><h2>Recent activity</h2><Activity icon={<ShoppingBag size={18} />} name="Order #OTF-1045" note="Completed" amount="-68.00 USDC" /><Activity icon={<BadgeDollarSign size={18} />} name="Affiliate reward" note="Order validated" amount="+12.40 USDC" positive /><Activity icon={<Wallet size={18} />} name="USDC deposit" note="Today" amount="+100.00 USDC" positive /></article></div><button className="text-button" onClick={onShop}>← Back to shopping</button></section>; }
function Activity({ icon, name, note, amount, positive = false }: { icon: React.ReactNode; name: string; note: string; amount: string; positive?: boolean }) { return <div className="activity"><span className={`activity-icon ${positive ? "reward" : ""}`}>{icon}</span><p>{name}<small>{note}</small></p><b className={positive ? "positive" : ""}>{amount}</b></div>; }

function CommunityView({ setNotice }: { setNotice: (text: string) => void }) { return <section className="app-page community-page"><div className="page-intro"><p className="eyebrow">OUTOUF COMMUNITY</p><h1>Style shared, rewards earned.</h1><p>Follow looks you love and build your own referral circle.</p></div><div className="community-grid"><article className="referral-card"><p className="eyebrow">YOUR REFERRAL LINK</p><h2>outouf.com/nora</h2><p>12 friends shopped through your link this month.</p><button className="primary-button" onClick={() => setNotice("Your referral link was copied.")}>COPY LINK</button></article><article className="rewards-card"><p className="eyebrow">AFFILIATE EARNINGS</p><h2>38.60 <span>USDC</span></h2><p>12.40 USDC is available after today’s validated order.</p><div className="progress"><i /></div></article></div><h2 className="feed-heading">From the community</h2><div className="feed"><Feed initials="ML" color="coral" title="Maya" detail="shared a look" sub="2h ago · Bags & scarves" likes="24" /><Feed initials="JR" color="blue" title="Jordan" detail="earned a reward" sub="5h ago · Order validated" likes="18" /><Feed initials="SK" color="yellow" title="Sofia" detail="saved a drop" sub="1d ago · Watches" likes="31" /></div></section>; }
function Feed({ initials, color, title, detail, sub, likes }: { initials: string; color: string; title: string; detail: string; sub: string; likes: string }) { return <article><div className={`avatar ${color}`}>{initials}</div><p><b>{title}</b> {detail}<small>{sub}</small></p><span>♡ {likes}</span></article>; }

function OrdersView({ validated, validateOrder }: { validated: string[]; validateOrder: (id: string) => void }) { return <section className="app-page orders-page"><div className="page-intro split"><div><p className="eyebrow">OPERATIONS</p><h1>Orders received</h1><p>Validate an order to release its affiliate reward automatically.</p></div><button className="secondary-button"><Package size={17} /> Export orders</button></div><div className="order-table" role="table" aria-label="Orders received"><div className="table-row table-head" role="row"><span>Order</span><span>Customer</span><span>Items</span><span>Affiliate</span><span>Total</span><span>Status</span></div>{orders.map((order) => { const done = validated.includes(order.id); return <div className="table-row" role="row" key={order.id}><strong>{order.id}</strong><span>{order.customer}</span><span>{order.item}</span><span>{order.affiliate}</span><strong>{order.total}</strong><span>{done ? <b className="validated"><Check size={14} /> Validated</b> : order.status === "Sourcing" ? <b className="sourcing">Sourcing</b> : <button className="validate-button" onClick={() => validateOrder(order.id)}>Validate order</button>}</span></div>; })}</div></section>; }
